server:
  port: 8989
  servlet:
    context-path: /flowable-modeler

spring:
  application:
    name: flowable-learn
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  jmx:
    default-domain: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable-learn?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: aaaaaa
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select count(1) from sys.objects Where type='U' And type_desc='USER_TABLE'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#mybatis
mybatis-plus:
  mapper-locations:
    - classpath:mybatis/mappers/*.xml
  typeAliasesPackage: com.honghh.bootfirst.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement

flowable:
  async-executor-activate: false
  database-schema-update: false
  common:
    app:
      idm-url: http://localhost:8080/flowable-idm
      idm-admin:
        user: damin
        password: 123456
  modeler:
    app:
      deployment-api-url: http://localhost:8080/flowable-task/app-api