spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable-learn?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aaaaaa
  application:
    name: flowable-modeler
  # SECURITY
  liquibase:
    enabled: false
  jmx:
    default-domain: ${spring.application.name}
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  custom-mybatis-mappers: com.top.flowable.learn.mappers.BeautyWorkFlowMybatisMapper
  custom-mybatis-x-m-l-mappers: mappers/BeautyWorkFlowMybatisMapper.xml
  idm:
    password-encoder: spring_bcrypt

server:
  port: 8989
